import { Card, Typography } from "antd";
import Head from "next/head";
import { IProduct, IProductPageProps, baseURL } from "../../../constants";

export default function ProductDetails({ product }: IProductPageProps) {
  return (
    <>
      <Head>
        <title>Product details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "space-between",
          marginTop: 20,
          gap: 10,
          padding: 20,
        }}
      >
        <div>
          <h2>Product details</h2>
          <img src={product.image} alt={product.productName} width={300} />
          <div>
            <Typography.Text>
              <b>Name:</b> {product.productName}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Category:</b> {product.category}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Status:</b> {product.status}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Price:</b> {`${product.price}$`}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Description :</b> {product.description}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Individual Rating :</b>{" "}
              {`${product.individualRating} out of 5 Stars`}
            </Typography.Text>
            <br />
            <Typography.Text>
              <b>Average Rating :</b>{" "}
              {`${product.averageRating} out of 5 Stars`}
            </Typography.Text>
            <Typography.Text>
              <h4>Key Features:</h4>{" "}
              <ul>
                {Object.entries(product.keyFeatures).map(([key, value]) => (
                  <li key={key}>
                    <strong>{key}:</strong> {value}
                  </li>
                ))}
              </ul>
            </Typography.Text>
            <Typography.Text>
              <h4>Reviews:</h4>
            </Typography.Text>
            {product.reviews.map((review, index) => (
              <Card key={index}>
                <b>{review.userName}</b>
                <br />
                <Typography.Text italic>
                  {review.rating} out of 5
                </Typography.Text>
                <p>{review.reviewText}</p>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
export async function getStaticProps({ params }: any) {
  const res = await fetch(`${baseURL}/products/single/${params.id}`);
  const product = await res.json();
  return {
    props: {
      product: product[0],
    },
    revalidate: 10,
  };
}
export async function getStaticPaths() {
  const res = await fetch(`${baseURL}/products/all`);
  const products = await res.json();
  const paths = products.map((product: IProduct) => ({
    params: { id: product._id },
  }));

  return {
    paths,
    fallback: false,
  };
}
