import CpuCart from "@/components/BuilderCarts/CpuCart";
import PsuCart from "@/components/BuilderCarts/PsuCart";
import RamCart from "@/components/BuilderCarts/RamCart";
import SdCart from "@/components/BuilderCarts/SdCart";
import { Card } from "antd";
import Head from "next/head";

const Builder = () => {
  return (
    <>
      <Head>
        <title>Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card title="Builder" style={{ marginTop: 20 }}>
        <CpuCart />
        <RamCart />
        <PsuCart />
        <SdCart />
      </Card>
    </>
  );
};

export default Builder;
